### ISSUE TITLE
Search in fields other than headword and cf

### ISSUE THREAD

**Issue by raquel-ucl** [oracc/elastic-search-poc#3]
At the moment the search is just looking into those fields, but after talking with @stinney we also need to ingest:

- [x] entries.senses.mgn (meaning)
- [x] entries.gw (guide word)
- [x] entries.forms.n (lemmatisation?)
- [x] entries.norms.n

The senses contains a norms and forms properties which are redundant, and a sigs (signatures) properties that contains data already included in the fields we are searching for.

**Comment by ageorgou** [comment]
We should look into how ES does text search, especially how it breaks down words and other tokens. Searching for "water" in the headword misses some results -- possibly because of the trailing "]N"? Although searching for "water]N" returns extra results that are unrelated, like "large mortar]N", so maybe it returns approximate matches too?

**Comment by ageorgou** [comment]
The fields mentioned above are ingested and searched in the newest version. Results appear to match the ones produced by the website (http://build-oracc.museum.upenn.edu/neo/sux), for the examples I tried.
